[package]
name = "bot"
version = "0.1.0"
authors = ["quang"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.8"
rand = "0.7.3"
